export const INDUSTRIES = [
  "Healthcare",
  "Financial Services",
  "Technology",
  "SaaS",
  "E-commerce",
  "Education",
  "EdTech",
  "Manufacturing",
  "Real Estate",
  "Media & Entertainment",
  "Logistics",
  "Energy",
  "Oil & Gas",
  "Retail",
  "Consulting",
  "Legal",
  "Hospitality",
  "Cybersecurity",
  "Telecommunications",
  "Automotive",
  "Aerospace",
  "Construction",
  "Agriculture",
  "Government",
  "Nonprofit",
  "Pharmaceuticals",
  "Biotechnology",
  "Insurance",
  "Other",
] as const;

/** Extra terms that surface industries while typing in the combobox. */
export const INDUSTRY_SEARCH_ALIASES: Record<string, readonly string[]> = {
  Healthcare: ["health", "medical", "hospital", "pharma", "healthtech"],
  "Financial Services": ["finance", "fintech", "banking", "investment"],
  Technology: ["tech", "software", "it", "information technology"],
  SaaS: ["software as a service", "b2b software", "cloud software"],
  "E-commerce": ["ecommerce", "online retail", "marketplace"],
  Education: ["school", "university", "learning"],
  EdTech: ["education technology", "e-learning"],
  Manufacturing: ["industrial", "factory"],
  "Real Estate": ["property", "proptech", "reit"],
  "Media & Entertainment": ["media", "publishing", "gaming", "streaming"],
  Logistics: ["shipping", "freight", "supply chain"],
  Energy: ["utilities", "power", "renewable"],
  "Oil & Gas": ["petroleum", "oil", "gas"],
  Retail: ["consumer", "stores", "fashion"],
  Consulting: ["advisory", "professional services"],
  Legal: ["law", "attorney"],
  Hospitality: ["hotel", "restaurant", "travel", "tourism"],
  Cybersecurity: ["security", "infosec"],
  Telecommunications: ["telecom", "wireless", "5g"],
  Automotive: ["auto", "vehicles"],
  Aerospace: ["aviation", "defense"],
  Construction: ["building", "contractor"],
  Agriculture: ["farming", "agtech"],
  Government: ["public sector", "federal", "state"],
  Nonprofit: ["ngo", "charity"],
  Pharmaceuticals: ["pharma", "drug"],
  Biotechnology: ["biotech", "life sciences"],
  Insurance: ["insurer", "underwriting"],
};

export { COUNTRIES } from "@/lib/search/countries";

export const COMPANY_SIZE_PRESETS = [
  { label: "1 – 10", min: 1, max: 10 },
  { label: "11 – 50", min: 11, max: 50 },
  { label: "51 – 200", min: 51, max: 200 },
  { label: "201 – 500", min: 201, max: 500 },
  { label: "501 – 1,000", min: 501, max: 1000 },
  { label: "1,001 – 5,000", min: 1001, max: 5000 },
  { label: "5,000+", min: 5000, max: null },
] as const;

export const JOB_TITLE_SUGGESTIONS = [
  "CEO",
  "Chief Executive Officer",
  "CTO",
  "Chief Technology Officer",
  "CFO",
  "Chief Financial Officer",
  "COO",
  "Chief Operating Officer",
  "CMO",
  "Chief Marketing Officer",
  "CPO",
  "CHRO",
  "Founder",
  "Co-Founder",
  "President",
  "Managing Director",
  "Vice President",
  "VP",
  "VP Engineering",
  "VP Sales",
  "VP Marketing",
  "Director",
  "Executive Director",
  "Marketing Director",
  "Sales Director",
  "IT Director",
  "Head of Product",
  "Head of Engineering",
  "Head of Marketing",
  "Head of Sales",
  "Marketing Manager",
  "Product Manager",
  "Chairman",
  "Chairperson",
  "Board Member",
  "Partner",
  "Owner",
  "Manager",
] as const;

export const KEYWORD_SUGGESTIONS = [
  "SaaS",
  "B2B",
  "B2C",
  "software",
  "cloud",
  "startup",
  "enterprise",
  "fintech",
  "healthtech",
  "edtech",
  "proptech",
  "AI",
  "machine learning",
  "cybersecurity",
  "digital agency",
  "consulting",
  "e-commerce",
  "marketplace",
  "platform",
  "subscription",
] as const;

export const TECHNOLOGY_SUGGESTIONS = [
  "React",
  "Node.js",
  "Python",
  "AWS",
  "Azure",
  "Salesforce",
  "HubSpot",
  "Shopify",
  "WordPress",
  "Kubernetes",
  "Docker",
  "PostgreSQL",
] as const;
