import { normalizeCountryName } from "@/lib/search/country-aliases";

/** ISO 3166-1 alpha-2 codes for OpenCorporates country_code / jurisdiction filters. */
const COUNTRY_TO_ISO: Record<string, string> = {
  pakistan: "pk",
  "united states": "us",
  "united kingdom": "gb",
  india: "in",
  angola: "ao",
  canada: "ca",
  australia: "au",
  germany: "de",
  france: "fr",
  spain: "es",
  italy: "it",
  netherlands: "nl",
  sweden: "se",
  norway: "no",
  denmark: "dk",
  finland: "fi",
  ireland: "ie",
  switzerland: "ch",
  belgium: "be",
  austria: "at",
  poland: "pl",
  brazil: "br",
  mexico: "mx",
  argentina: "ar",
  chile: "cl",
  colombia: "co",
  "south africa": "za",
  nigeria: "ng",
  kenya: "ke",
  egypt: "eg",
  "united arab emirates": "ae",
  "saudi arabia": "sa",
  singapore: "sg",
  malaysia: "my",
  indonesia: "id",
  philippines: "ph",
  thailand: "th",
  vietnam: "vn",
  japan: "jp",
  china: "cn",
  "south korea": "kr",
  "new zealand": "nz",
  bangladesh: "bd",
  "sri lanka": "lk",
  nepal: "np",
  turkey: "tr",
  portugal: "pt",
  greece: "gr",
  czechia: "cz",
  "czech republic": "cz",
  romania: "ro",
  hungary: "hu",
  ukraine: "ua",
  israel: "il",
  taiwan: "tw",
  "hong kong": "hk",
};

/** Wikidata country entity (P17) for SPARQL directory queries. */
const COUNTRY_TO_WIKIDATA: Record<string, string> = {
  pakistan: "Q843",
  "united states": "Q30",
  "united kingdom": "Q145",
  india: "Q668",
  angola: "Q916",
  canada: "Q16",
  australia: "Q408",
  germany: "Q183",
  france: "Q142",
  sweden: "Q34",
  norway: "Q20",
  denmark: "Q35",
  finland: "Q33",
  ireland: "Q27",
  switzerland: "Q39",
  brazil: "Q155",
  mexico: "Q96",
  japan: "Q17",
  china: "Q148",
  singapore: "Q334",
  "united arab emirates": "Q878",
  "saudi arabia": "Q851",
  "south africa": "Q258",
  netherlands: "Q55",
  spain: "Q29",
  italy: "Q38",
  belgium: "Q31",
  austria: "Q40",
  poland: "Q36",
  bangladesh: "Q902",
  indonesia: "Q252",
  malaysia: "Q833",
  philippines: "Q928",
  thailand: "Q869",
  vietnam: "Q881",
  "south korea": "Q884",
  "new zealand": "Q664",
  turkey: "Q43",
  israel: "Q801",
  argentina: "Q414",
  chile: "Q298",
  colombia: "Q739",
  nigeria: "Q1033",
  kenya: "Q114",
  egypt: "Q79",
};

export function countryToIsoCode(country: string): string | null {
  const normalized = normalizeCountryName(country);
  if (!normalized) return null;
  return COUNTRY_TO_ISO[normalized] ?? null;
}

export function countryToWikidataId(country: string): string | null {
  const normalized = normalizeCountryName(country);
  if (!normalized) return null;
  return COUNTRY_TO_WIKIDATA[normalized] ?? null;
}
